name: Preview Clean
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  clean:
    name: Clean Preview Environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.117
      - run: |
          flyctl apps list --json \
            | jq '[
                .[]
                  | { ID:.ID, LastReleasedAt: .CurrentRelease.CreatedAt }
                  | select(.ID | test("^cashfolio-preview-[0-9a-f]{8}$"))
              ]
                | sort_by(.LastReleasedAt)
                | reverse
                | .[3:]
                | map(.ID, .ID + "-db")
                | .[]' \
              | xargs -I {} flyctl apps destroy --yes {}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
